import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/header/header";
import Navbar from "../components/Navbar";
import List from "../components/List";
import request from "../base/request";
import Footer from "../components/Footer";

export async function getServerSideProps(context) {
    const genre = context.query.genre

    const req = await fetch(
        `https://api.themoviedb.org/3${
            request[genre]?.url || request.fetchTrending.url
        }`
    ).then(res => res.json())

    return{
        props: {
            results: req.results
        }
    }
}

export default function Home({results}) {
    console.log(results)
    return (
        <>
            <Head>
                <title>Hulu Clone</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.1.1/css/all.css" />
            </Head>
            <Navbar />
            <List results={results}/>
            <Footer />
        </>
    )
}
